### ISSUE TITLE
No library found for Jama

### ISSUE THREAD

**Issue by juanalverto** [genekogan/KinectProjectorToolkit#17]
Hello i am having this issue at run the Calibration file:

"No library found for Jama
Libraries must be installed in a folder named 'libraries' inside the 'sketchbook' folder."

¿Anyone knows how to fix it? In the video example the code does not have this line of code that imports that Jama Library.

"import Jama.*;"

I download the package and put it with the other libraries and the code still telling me the same problem..

cheers!

**Comment by genekogan** [comment]
the file `Jama-1.0.3.jar` is in the `libraries` folder of the library. do you have the library properly installed? make sure the whole folder is inside your libraries folder and it should be found.
