### ISSUE TITLE
chessboard window on my computer screen

### ISSUE THREAD

**Issue by jing1234** [genekogan/KinectProjectorToolkit#19]
Hi,
when i run the calibration code, why the chessboard always on my computer screen but not the projector screen. And it can not be dragged and moved. So i can't use the calibration toolkit. Anybody can help me?
Thanks so much.

**Comment by genekogan** [comment]
in display settings, make sure your projector monitor is to the right of your computer screen monitor, not to the left. the way it positions the chessboard window is by translating to the right, the entire width of your monitor.  this is a common mistake.

**Comment by jing1234** [comment]
@genekogan,Thanks so much, i change the display setting. But i meet another problem now.  i can't use the chessboard window. it can only be found in the toolbar. It can not be opened. So i can only see the calibration window on my computer screen and projector screen. Can you help me?

Thanks

**Comment by jing1234** [comment]
![dispaly setting](https://cloud.githubusercontent.com/assets/18555526/23467963/be52f73e-fe9f-11e6-8136-c1c83956f666.png)
I think, i did the right display setting. And i checked the second screen was the projector screen. But the chessboard is still on my computer screen, and it can not be dragged or moved. And the calibration window in the projector screen, but it can be dragged to my computer screen. How it happens? Can you help me?

Best Wishes and Thanks,
Jing

**Comment by jing1234** [comment]
Maybe i have not correct describe my problem。 The Chessboard window is half on my computer screen and the other half on the projector screen. Why?

**Comment by genekogan** [comment]
i don't know. take a look at [Util.pde](https://github.com/genekogan/KinectProjectorToolkit/blob/master/examples/CALIBRATION/Util.pde) where it sets the the x,y,width,height of the projector window in the line `setBounds(displayWidth,0,pWidth,pHeight);`.  `displayWidth` is supposed to be the width of the first screen. maybe processing is not calculating it correctly i don't know, but you can just set it manually by replacing it with whatever the width of your monitor is.

**Comment by jing1234** [comment]
OK, Thanks so much.
