### ISSUE TITLE
Mapping image is too small

### ISSUE THREAD

**Issue by eighteight** [genekogan/KinectProjectorToolkit#25]
I have done a calibration, getting this matrix:
<CALIBRATION>
	<COEFF0>2.74607e-05</COEFF0>
	<COEFF1>-3.65818e-05</COEFF1>
	<COEFF2>-0.000119975</COEFF2>
	<COEFF3>0.504437</COEFF3>
	<COEFF4>1.13116e-05</COEFF4>
	<COEFF5>-1.49632e-05</COEFF5>
	<COEFF6>-0.000132833</COEFF6>
	<COEFF7>0.541646</COEFF7>
	<COEFF8>2.27564e-05</COEFF8>
	<COEFF9>-7.33312e-05</COEFF9>
	<COEFF10>-0.00024209</COEFF10>
</CALIBRATION>

Now, I am projecting back on a figure (of Vsevolod Meyerhold), but the blob, which corresponds to the figure is too small in the projection:

<img width="1262" alt="screen shot 2017-10-08 at 4 29 17 pm" src="https://user-images.githubusercontent.com/542368/31317291-d2d40b08-ac46-11e7-95b8-f5e07f88dc97.png">

Also, I don't understand what are those rays coming out of the figure blob.

Any insight would be much appreciated.

**Comment by genekogan** [comment]
i don't know what you might be doing wrong. make sure you have set the width and height of the window in the test app to match your projector, that would cause mapping errors. the other rays are the other blobs that you found  (like the desk).

**Comment by eighteight** [comment]
Thanks. I simply re-calibrated kinect using a larger area (I moved that white board around the room for that) and the mapping became perfect.
