### ISSUE TITLE
Error to run the sketch with processing 2 and processing 3

### ISSUE THREAD

**Issue by MatteoSupertramp** [genekogan/KinectProjectorToolkit#28]
Hello, first of all I'm just getting started with processing and code, so I'm sorry if this comment will look stupid.
I tried to run the sketch with processing 2.2.1 and it gave an error: 
 _**" This version of Processing only supports libraries and JAR files compiled for Java 1.6 or earlier.
A library used by this sketch was compiled for Java 1.7 or later, 
and needs to be recompiled to be compatible with Java 1.6."**_
So I tried to run the sketch with Processing 3 and it gave another error:
_**"The method add(Component) in the type Container is not applicable for the arguments (CALIBRATION.ChessboardApplet)"**_

What can I do? Do I have to download some precise libraries, or something similar?
I'm using MacBook Pro macOS ventura 13
pls help
sorry for my English

**Comment by genekogan** [comment]
I'm sorry, this library was made almost 10 years ago and I'm not really maintaining it anymore.  
it was made for processing 2.2.1, and doesn't work on 3 (although there might be a fork that does).
also it only works on the original Kinect which is no longer manufactured...
