### ISSUE TITLE
Unmentioned Jama dependency?

### ISSUE THREAD

**Issue by stuartlynn** [genekogan/KinectProjectorToolkit#5]
It looks like the calibration script requires Jama https://github.com/genekogan/KinectProjectorToolkit/blob/master/examples/CALIBRATION/CALIBRATION.pde#L16 as a dependency which isn't mentioned anywhere in the docs. Including the jar from [http://www.jamasoftware.com/](http://www.jamasoftware.com/) in the sketch seems to fix this issue. 

If this is actually the case and I am not doing something wrong it might be worth mentioning in the ReadME. Happy to write something up and send it in a pull request.

**Comment by genekogan** [comment]
jama is included in the library folder. adding the library as you normally would a library in processing should include it.
