### ISSUE TITLE
Getting error on guiCpos.arrayValue() should be guiCpos.getArrayValue()

### ISSUE THREAD

**Issue by stuartlynn** [genekogan/KinectProjectorToolkit#6]
In the calibration script GUI I get an error about arrayValue not being a function on guiCpos in the following lines: 

https://github.com/genekogan/KinectProjectorToolkit/blob/master/examples/CALIBRATION/GUI.pde#L75-L76

Changing this to gui.getArrayValue() (which seems to be documented in the controlP5 docs http://www.sojamo.com/libraries/controlP5/reference/controlP5/Slider2D.html) seems to fix the issue. 

This might be a versioning issue? If its not happy to write up a quick PR to make this change.

**Comment by genekogan** [comment]
yes, this is an issue because i wrote the library using an older version of controlP5.  a PR would be great!

**Comment by stuartlynn** [comment]
Sounds good. Will send through shortly.
