### ISSUE TITLE
Trouble getting checkerboard to show up on projector

### ISSUE THREAD

**Issue by stuartlynn** [genekogan/KinectProjectorToolkit#7]
I am having issues with the calibration script. I can't get the second display with the chessboard to show anything. The GUI appears and seems to work perfectly but no other window either on the primary or secondary display. Do I have to do something special to get the secondary display in processing? Using processing 2.2.1 on OS X.

Any help appreciated.

**Comment by genekogan** [comment]
check out the [tutorial](https://vimeo.com/84658886). you probably have your display settings off. the window should show up to the monitor to the right of your laptop screen so make sure your projector is set to that position.

**Comment by stuartlynn** [comment]
Will give that a try thanks!

**Comment by stuartlynn** [comment]
Thats got it thank you. I might submit a quick PR with that as an update in the readme file just so its clear.
